// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Candidate } from "./Candidate";
import type { Provenance } from "./Provenance";

/**
 * Ambiguous stable ID result.
 */
export type AmbiguousStableId = { path: string, stable_id: string, candidates: Array<Candidate>, reason: string, provenance: Provenance, };
