// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AstCell } from "./AstCell";
import type { OmittedChunk } from "./OmittedChunk";
import type { Provenance } from "./Provenance";

/**
 * Successful bundle result.
 */
export type Bundle = { version: number, path: string, cells: Array<AstCell>, omitted: Array<OmittedChunk>, provenance: Provenance, };
