// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AmbiguousStableId } from "./AmbiguousStableId";
import type { Bundle } from "./Bundle";
import type { Exhausted } from "./Exhausted";
import type { NotFound } from "./NotFound";
import type { UnknownCrossFile } from "./UnknownCrossFile";

/**
 * Union of all possible v1 results.
 */
export type BundleResult = { "kind": "bundle" } & Bundle | { "kind": "not_found" } & NotFound | { "kind": "ambiguous_stable_id" } & AmbiguousStableId | { "kind": "exhausted" } & Exhausted | { "kind": "unknown_cross_file" } & UnknownCrossFile;
