// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Candidate for ambiguous stable ID resolution.
 */
export type Candidate = { anchor_byte: number, kind: string, name: string | null, };
