// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OmittedChunk } from "./OmittedChunk";
import type { Provenance } from "./Provenance";

/**
 * Exhausted budget result.
 */
export type Exhausted = { path: string, stable_id: string, omitted: Array<OmittedChunk>, provenance: Provenance, };
