// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A chunk that was omitted from the bundle.
 */
export type OmittedChunk = { stable_id: string, reason: string, };
