// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";

/**
 * Provenance metadata attached to every result.
 */
export type Provenance = { strategy: string, confidence: Confidence, graph_snapshot_id: string, orientation_freshness: string, };
