// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unknown cross-file reference result.
 */
export type UnknownCrossFile = { path: string, stable_id: string, reason: string, };
